### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Neumann-Nils** [Neumann-Nils/hofbox-orchestration#3]
- [x] Scoring-System in README beschreiben
- [x] Einstellungen für Scoring in JSON auslagern
- [x] Tooltip für Bewertungssystem (A-F)
- [x] Add conclusion to "Analyse bestehender Lösungen"
- [x] Patch
- [x] Add tooltip for grading factor
- [x] Abschlussbericht
- [x] Abschlusspräsentation
